# Generated by Django 4.1.4 on 2022-12-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Noticias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticias',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
